FROM node:20-slim 
# debian

# RUN apt update -y && \
#     apt install -y procps && \
#     npm install -g @nestjs/cli@10.0.0

USER node

WORKDIR /home/node/app



CMD [ "/home/node/app/.docker/start.sh" ]